### ISSUE TITLE
画像の命名規則の統一

### ISSUE THREAD

**Issue by naogify** [jawordpressorg/user-manual#115]
画像の命名規則が決まっていないので、統一した方が良いかと思います。
（ex, 3-1.png、update01.pngなど）

いかがでしょうか？

**Comment by naogify** [comment]
命名案として、

セクションタイトル名のフォルダを作成し、画像には連番を振るのはどうでしょうか?
（ex, images/login/01.png）

理由としては、、
・セクションの追加、削除が容易かなと。

**Comment by tekapo** [comment]
セクションタイトル名は後から修正変更が入る可能性があるかなと。
じゃあどうすれば、という案はないんですが。。。

**Comment by naogify** [comment]
セクションタイトル名の修正変更が入っても、
フォルダ名を書き換えるだけなので、修正は容易かと思います。どうでしょうか?

**Comment by miya0001** [comment]
@naogify 
ご意見ありがとうございます！

オープンソースコミュニティで毎回違うメンバーが出入りするプロジェクトであるため何かルールを決める場合はすべてどこかに明文化する必要があります。でないとルールの存在自体に意味がなくなってしまいます。
複数のページから一つの画像を読み込んでいるケースなどなどなど不確定な要素も多いように感じます。
そしてコスト的にもあまり意味がない気がします。

というわけで閉じます！
