### ISSUE TITLE
copyrightとリンクは2016⇒2017にすべきでしょうか

### ISSUE THREAD

**Issue by yorikotsudajp** [jawordpressorg/user-manual#118]
各ページ下のcopyrightは

Organized by WordCamp Kansai 2016 documentation Hands-on team. / licensed under the GPLv2 or later.

WordCamp Kansai 2016 ドキュメンテーションハンズオンチームが運営しています。

となっていますが、「2017」にすべきでしょうか?
リンク先も2016になっています。

**Comment by yat8823jp** [comment]
copyright は著作権が発生した年を記載して、それ以降は変える必要が無いので、そのままでいいと思います。

**Comment by ixkaito** [comment]
thanks
