### ISSUE TITLE
コントリビューターの名前の列記

### ISSUE THREAD

**Issue by megane9988** [jawordpressorg/user-manual#46]
フッターか、別ページか。
ページ上に以下の内容を反映させる

https://github.com/wckansai2016/wordpress-document/network/members

**Comment by mayukojpn** [comment]
案1:
[Github API でとってこれる](https://api.github.com/repos/wckansai2016/wordpress-document/contributors)ので、Jekyll のテンプレートで表示のカスタマイズをする。

**Comment by megane9988** [comment]
@mayukojpn  APIからの表示できます？それならお願いしたいですー

**Comment by mayukojpn** [comment]
やったー！やってみます！

**Comment by mayukojpn** [comment]
コミットメッセージに id かくのわすれました。。。
https://github.com/wckansai2016/wordpress-document/pull/84

Jekyll で API とってこれるのかわからなかったので、Riot.js をいれました。もしかしたら不要かもしれませんがよろしくおねがいします。
