### ISSUE TITLE
README.md にこのプロジェクト自体への参加方法がほしい。

### ISSUE THREAD

**Issue by ShinichiNishikawa** [jawordpressorg/user-manual#50]
- フォークしてプルリク送ってね、的なこと。
- 目次はあるのかな。それを見てやれそうなやつを送って、とか。
- ページを増やしたいと思った時に、参加のルールが分からないので、誰に聞けばいいのか？とか書いてあると嬉しい

**Comment by mayukojpn** [comment]
CONTRIBUTING.md というファイル名で分けておくと、プルリクを送るときなどにリンクが表示されるようです。英語ですが。。。[_s](https://github.com/Automattic/_s/blob/master/CONTRIBUTING.md) とか [Twenty Sixteen](https://github.com/WordPress/twentysixteen/blob/master/CONTRIBUTING.md) にも入ってましたよね。

![CONTRIBUTING.md preview](https://camo.githubusercontent.com/71995d6b0e620a9ef1ded00a04498241c69dd1bf/68747470733a2f2f6769746875622d696d616765732e73332e616d617a6f6e6177732e636f6d2f736b697463682f6973737565732d32303132303931332d3136323533392e6a7067)
出典: https://github.com/blog/1184-contributing-guidelines

**Comment by nukaga** [comment]
ちょっと試してみます。

**Comment by nukaga** [comment]
作成。
https://github.com/wckansai2016/wordpress-document/blob/gh-pages/CONTRIBUTING.md
README.mdからリンクしてます。
不足あれば追記お願いします！
