### ISSUE TITLE
jawordpressorgへの移管

### ISSUE THREAD

**Issue by hideokamoto** [jawordpressorg/user-manual#55]
継続的にメンテすることを考えると、WordCamp Kansai2016のリポジトリからWordPress 日本語版作成チームのリポジトリに移管させた方が良いかもしれませんね。
https://github.com/jawordpressorg

**Comment by nukaga** [comment]
うーん、できたら良いなとは思うのですが、どうなのかな？日本語チームさんに聞いてみますね。

**Comment by nukaga** [comment]
少し考えたのですが、もう少し形になってから移管のお話をした方が良いように思いました。
マージなどの作業負担が管理者さんにかかってしまうので、一旦今やっているものが形になってからの方が良いかなあと。

**Comment by tekapo** [comment]
WordCamp京都2017が終わったら移管をすすめましょう。

**Comment by tekapo** [comment]
以下にフォークしましたー!
https://github.com/jawordpressorg/user-manual
