### ISSUE TITLE
kramdown への移行

### ISSUE THREAD

**Issue by mayukojpn** [jawordpressorg/user-manual#56]
いきなり小難しいイシューですみません。

[GitHub 公式のブログ記事](https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0)によると、2016年5月1日以降は `kramdown` のみが GitHub ページのマークアップ言語として対応と書いてあります。

いま [Redcarpet をお使いですが](https://github.com/wckansai2016/wordpress-document/blob/gh-pages/_config.yml)、フォークして最初にコミットをプッシュすると、全員にお知らせメールが送られてしまってるようです。できれば直した方がいいかと思います。

ついでに、送られてくるメールのコピー
（件名: `[mayukojpn/wordpress-document] Page build warning`）

> The page build completed successfully, but returned the following warning:
> 
> You are currently using the 'redcarpet' Markdown engine, which is no longer supported by GitHub Pages and may cease working at any time. To ensure your site continues to build, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by nukaga** [comment]
これって、ガイドページにあるような`markdown:`部分を`kramdown`に変えるだけでいいのかな？
ちょっと詳しくなくて申し訳ないです。

**Comment by mayukojpn** [comment]
はい！そうなんですが、マークダウンが効かなくなるページが有るので、よかったら私の方でまとめて修正してしまおうかなと思いました！

私のリポジトリにて一部反映していて、たとえば[このページ](https://mayukojpn.github.io/wordpress-document/6_user/)だと、シャープとタイトルの間に半角スペースが入ってないのでタイトルと認識されてません。

**Comment by nukaga** [comment]
ありがとうございます！
そうか、Forkしたリポジトリで試してみれば良いのですね。

**Comment by mayukojpn** [comment]
はい！GitHub Pages つかうのに設定が必要かもしれませんが！
こちら、なるはやで消化してしまいます、すみません m(_ _)m
