### ISSUE TITLE
dl / dt / dd タグのあとのマークアップが反映されていない

### ISSUE THREAD

**Issue by mayukojpn** [jawordpressorg/user-manual#60]
1760352f34770ba81d787a090144e861142d4763 マークアップ言語の変更を行ったところ、[一般設定](https://wckansai2016.github.io/wordpress-document/7_settei/)ページのマークアップが一部反映されなくなってしまいました。
関連: #59

**Comment by hinaloe** [comment]
dl閉じてないからかな、なおしますね

**Comment by mayukojpn** [comment]
ねね、なんか変じゃない？kramdown について読まないといけなそう。
http://hnle.tk/wordpress-document/7_settei/

ところで GitHub Pages で独自ドメイン使えるんだね(・∀・)

**Comment by hinaloe** [comment]
dt開いてdd閉じようとしていた模様。

**Comment by mayukojpn** [comment]
よく気づきましたね！ありがとうございます 👍
