### ISSUE TITLE
管理画面のメニューを表す用語の統一

### ISSUE THREAD

**Issue by torounit** [jawordpressorg/user-manual#73]
管理画面のメニューを表現する言葉が何種類か存在している。(ex メニュー・左ペイン...）まとめた方がよさそう

**Comment by nukaga** [comment]
確かに。あと「管理画面」「ダッシュボード」も混在してますね。
https://wpdocs.osdn.jp/管理画面
「メニュー」で統一が良さそうです。

https://wpdocs.osdn.jp/Codex:揺らぎ対策本部

**Comment by Takao-KONDO** [comment]
「メニュー」への統一ですと、個人的には「外観」＞「メニュー」の「メニュー」との混乱の可能性が少し引っかかります。大概大丈夫でしょうが。

**Comment by nukaga** [comment]
先にリンクを貼ったようにもともと統一された語句があり、それに合わせるのが良いかと思いました。

**Comment by Takao-KONDO** [comment]
私がリンク先の見方が分かっていないのかもしれませんが、リンク先ページを拝見しても、そのように統一されているとも、統一が成功しているとも読み取れませんでした。
少なくとも、左サイドのメニュー領域全域について指すものとしては、「メインナビゲーション」という用語が使われており、それは英語版からの一対一の直訳になっていると思います。「左ペイン」という表現が必要な文脈があるとすれば、そこは「メインナビゲーション」、あるいは「左側のメインナビゲーション」という表現をするなら、Codexとの矛盾は生じないように見えます。
「メニュー」という用語は、メインナビゲーションの中の各メニュー項目を指すものとして、「メインナビゲーションメニュー」などの表現で使われているように見えます。そのように、どこのメニューか、を示唆できる文脈の中で使われるのでしたら「メニュー」で全く何も問題がありませんが、そうでなければ混乱の可能性が否定できません。
ですので、「左ペイン」などの表現を含めてすべて「メニュー」という一語に統一することは、かえって分かりやすさを減らすように思います。逆に複数の言い方が混在しても、それぞれが同じものを指すとして混乱しないならば、統一する必要があるのか、私には分かりません。
もちろん、最終判断はモデレータの皆様にお任せします。

**Comment by nukaga** [comment]
反応が遅くなってすみません！

管理画面の左側メニュー
→メインナビゲーションメニュー

メインナビゲーション内各メニュー
→メニュー

管理画面／ダッシュボード／管理パネル
→管理画面 

で統一が良いと思いました。
もしわかりにくいようであれば「文言について」的なメニューをドキュメントへ足しても良いかもしれませんね。

他の方、他のモデレーターさんの意見もしばし待ちますー。

**Comment by miya0001** [comment]
こういうディスカッションはプルリクドリブンでやるようにしましょう。
意見のやりとりだけで誰の目から見ても完璧なものをつくることは不可能なので、プルリクエストなどの方法で具体的な提示があった時に検討するようにするのが良いかと思います。
というわけで、だれも結論がだせないようなので閉じます。笑
