### ISSUE TITLE
リポジトリ名について

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/user-manual#77]
document はただの書類や記録の意味なので、説明書、手引書なら documentation の方がいいと思います。長くなるので、doc とか manual でもいいかもしれません。

**Comment by Takao-KONDO** [comment]
私はそもそもGitHubについてよく分かってもいない現状ですが、リポジトリ名については、薄々「何の文書だというつもりか」と思っていました。後から分かりにくくなるような気がするので、より趣旨の明確なものに変えられるものなら、変えることに賛成します。

**Comment by nukaga** [comment]
それであれば変えるのに私は賛成します。
・documentation 
・doc
・manual 
どれが良いってありますかね？

個人的には短い“doc”が良いなと思いました。

**Comment by hideokamoto** [comment]
ストレートに"user-manual"とか"user-guide"とかの方がわかりやすいかもですね。

**Comment by ixkaito** [comment]
ロゴに user manual って書いてあるから user manual でいいかも

**Comment by hideokamoto** [comment]
`wordpress-user-manual-ja`とかにします？

**Comment by tekapo** [comment]
WordCamp 京都2017が終わったらwordpress-user-manual-jaにしましょう。

**Comment by tekapo** [comment]
WordCamp Tokyo 2017終わったら。。

**Comment by showw** [comment]
WordCampTokyo2017で作ったWordSlackのチャンネル名がja-docsなんですが、これもリポジトリ名と同じにした方がいいかと思います。

**Comment by miya0001** [comment]
これついでにリポジトリを引っ越したほうがよくないですか？
https://github.com/jawordpressorg

WapuuのAPIのプルリクの相手がしんどいんですよね。。。ｗ

**Comment by miya0001** [comment]
そしたらリポジトリ名は単なる `user-manual` とかでよくなりますよね。
https://github.com/jawordpressorg/user-manual
みたいな。

仮に`documentation`でも今のリポジトリのURLより断然わかりやすくなります。

**Comment by tekapo** [comment]
移管はこちらで
https://github.com/wckansai2016/wordpress-document/issues/55

リポジトリ名は @miya0001 さんのいうようにuser-manualで良さそうですね。

**Comment by tekapo** [comment]
リポジトリ名変更し、以下にフォークしました。
https://github.com/jawordpressorg/user-manual

**Comment by miya0001** [comment]
あっ、フォークするとStarとかそのままなのと結局こっちがオリジナルになってしまうので、完全に移しちゃうのがいいかなと思います。
そうすると現在のこのリポジトリにアクセスしてもGitHubがリダイレクトしてくれます。
あとStarとか git remote とかも同様にぜんぶリダイレクトなり引き継ぐなりうまいことやってくれますので。

あっ、もしかして両方に権限があるのが僕だけかな。
もし問題がなければ僕がやります。

**Comment by miya0001** [comment]
移行すればこのリポジトリへコミット権限を持ってる人はアウトサイドコラボレータとしてついてくるはず。

**Comment by tekapo** [comment]
@miya0001 お願いしやす!

**Comment by tekapo** [comment]
@showw slackのチャンネルもリネームしました!

**Comment by miya0001** [comment]
移動完了したので閉じます。
コラボレータはついてこなかったのでとりあえず @megane9988 、 @ixkaito をコミッターとしてアサインしておきました。
他のコミッターが必要な場合は、 @tekapo または @nukaga または僕に知らせてください。
