### ISSUE TITLE
サイト内リンクについて

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/user-manual#78]
サイト内リンクが相対パスになっているところが多いですが、これに統一するということであればそれでもいいと思いますが、 `<a href="{{ site.baseurl }}/foo/bar">` のように、どのページにいても同じように書ける `site.baseurl` を使った書き方がおすすめです。

**Comment by nukaga** [comment]
`site.baseurl`は jekyll 固有の書き方でしょうか？
それで他の環境では使いにくいなあってことは無さそう？
不勉強で申し訳ないのですが、教えて頂けるとありがたいです。
そっちの方がメリットあるよーってことでしたら、私は良いと思います。

**Comment by ixkaito** [comment]
他の環境とは例えばどのようなものでしょうか？

`site.baseurl` はもちろん Jekyll 固有の書き方ですが、現在 Jekyll でヘッダー、フッター、サイドバーをインクルードしてますので、そもそも Jekyll を使うのをやめることは難しいと思いますが。

ちなみにビルドされたあとのファイル (`_site` の中) は普通の静的ファイルなので、別にどこにでも持っていけますよ。

一応プルリク送っておきました。 #83

**Comment by nukaga** [comment]
他の環境の想定は、例えばこのドキュメントを使いたい方がまとめてダウンロードして、ローカルで開く…というようなことを考えていました。

> ビルドされたあとのファイル (`_site` の中) は普通の静的ファイルなので、別にどこにでも持っていけますよ。

ということで問題無さそうと思ったのですが、`_site`がどこにあるのかわかりません…教えてカイトさん！
（ダウンロードしての使い方をどこかに追記できたらいいなと思いました）

**Comment by ixkaito** [comment]
ローカルで `jekyll s` もしくは `jekyll b` すると `_site` フォルダができます。本来はそれをサーバ上に置くことで、サイトが見れるようになるのですが、GitHub Pages は Jekyll プロジェクト自体をプッシュすることでそこらへんを自動的にやってくれます。

Jekyll があればローカルで開くことはできますが、そんなに需要あるかな…
ちなみに共通のサイドバーメニューでは、どうしても絶対パスで記述する必要があるので、ビルド済みの静的ファイルを用意したところで、ローカルにダウンロードしてもローカルサーバ建てないと見れませんけどね。

**Comment by nukaga** [comment]
教えてもらった内容だと、現状既にローカルでもローカルサーバ建てないとということで、マニュアルとして共有するにはURLを伝えてみてもらう形がスムーズなのかなと思いました。
というわけで、作り方としては`site.baseurl`を使う方向で統一するとして、マージしました。
ありがとうございました！

**Comment by ixkaito** [comment]
ありがとうございます！
ちなみにみんなのプルリクでリンク切れがよく発生しますので、このリポジトリの管理者に追加してもらえれば、簡単なテストを実装させていただきます。

**Comment by nukaga** [comment]
ありがとうございます！
管理者に追加しました。

**Comment by ixkaito** [comment]
ありがとうございます！テスト実装しました。
