### ISSUE TITLE
assets の管理について

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/user-manual#82]
現在 `assets` フォルダの中に `css` フォルダがあるが、なぜかその外にも `stylesheets` フォルダがあって、`images` フォルダも `assets` の中に入っていないので、ここらへんは統一した方がいいでしょう。

一つ質問ですが、各メニューのディレクトに `images` フォルダがありますが、これはこうしようと決めたんですか？`site.baseurl` で参照しにくいので、一つのフォルダにまとめたほうがいいかなと。

**Comment by Takao-KONDO** [comment]
> 一つ質問ですが、各メニューのディレクトに `images` フォルダがありますが、これはこうしようと決めたんですか？

まだどなたもお答えにならないので、一応、GitHub Pages初心者かつハンズオン一般参加者だった者からの見解です。ハンズオン当日、各個人が各々ディレクトリを割り当てられて別々に作業するという流れの中で、各ディレクトリ内で画像の命名を好き勝手にしても問題が起こらないように、ディレクトリ内のフォルダ名だけ統一する形にしていたのではという気がしています。割り当てが回ってくる前にどんな議論があったのかは、全く聞こえていませんでした。

**Comment by ixkaito** [comment]
@Takao-KONDO なるほど。ありがとうございます。
