### ISSUE TITLE
Riot.js が IE9 で動いてるかどうか？

### ISSUE THREAD

**Issue by ixkaito** [jawordpressorg/user-manual#87]
IE9 でフッターのコントリビューターのアバターが表示されてるかどうか、どなたか確認していただけますでしょうか？

**Comment by Takao-KONDO** [comment]
表示されていませんでした。（Windows Vista Home Premium ＋ IE9）

**Comment by ixkaito** [comment]
@Takao-KONDO ありがとうございます！
